const data=[
{
    id:1,
    title:'blog app',
    desc:`It is a information sharing website where people can share their views or can learn from other’s experineces.`,
    impact:['Authentication','Validations','Picture uploading','Storing Hashed password in db','Modern UI','Responsive'],
    tags:['html','css','bootstrap','js','react js','node js','express js','mongoDB'],
    ss:['/images/b1.png','/images/b2.png','/images/b3.png','/images/b3.png','/images/b4.png','/images/b5.png','/images/b6.png','/images/b7.png','/images/b8.png'],
    image:'/images/b1.png',
   },
{
    id:2,
    title:'job portal website',
    desc:`It is a website for job seekers where they can apply for jobs according to their choice`,
    impact:['Authentication',
        'Autharizations',
        'Validations',
        `4 level hierarchy   (super admin, admin ,hr ,user)`,
        'Responsive',
        'Modern UI',
        'Secure password in DB',
        'Forget password',
        'Automatic email sending after HR approved your application',
        'Popup messages for better user experience' 
        ],
    tags:['html','css','bootstrap','js','react js','node js','express js','mongoDB'],
    ss:['/images/picture1.png','/images/picture2.png','/images/picture3.png','/images/picture4.png','/images/picture5.png','/images/picture6.png','/images/picture7.png','/images/picture8.png'],
    image:'/images/picture1.png',
   },
{
    id:3,
    title:'todo app',
    desc:'this is vaery cool app',
    impact:['html','css'],
    tags:['html','css','bootstrap','js','react js','node js','express js','mongoDB'],
    ss:['/images/t1.png','/images/t2.png','/images/t3.png','/images/t4.png','/images/t5.png','/images/t6.png'],
    image:'/images/t1.png',
   },
{
    id:4,
    title:'contact book',
    desc:`This is an application where a user can store their important contacts and can edit or delete it according to their requirements.`,
    impact:['Save contact','Edit contact','Delete contact'],
    tags:['html','css','bootstrap','js','react js','redux','node js','express js','mongoDB'],
    ss:['/images/c1.png','/images/c2.png','/images/c3.png'],
    image:'/images/c1.png',
   },
{
    id:5,
    title:'student records',
    desc:`This  is an application where a school / college institute can store the records of students .`,
    impact:['Save students records ','Edit student information','Delete student record','Filter buttons for easy access'],
    tags:['html','css','bootstrap','js','react js','node js','express js','mongoDB'],
    ss:['/images/s1.png','/images/s2.png','/images/s3.png'],
    image:'/images/s1.png',
   },

]

export default data